<?php if (!defined("BASEPATH")) exit("No direct script access allowed");
// Clothing	
// type = S
// type_sub = CL
$lang["clothing_items"] = array("anklet","anorak","apparel","apron","armscye","ascot","balaclava","beanie","belt","beret","bikini","blouse","boater","boots","bowler","bowtie","boxers","bra","bracelet","braces","brassiere","briefs","button","camisole","cardigan","chemise","clogs","coat","collar","coonskin","corset","costume","cufflinks","deerstalker","dress","dressing-gown","earrings","fedora","fez","flats","flip-flops","flipflops","frock","g-string","galoshes","gatsby","glengarry","gloves","gown","hat","hats","heels","high-tops","jackboots","jacket","jeans","jersey","jewelry","kepi","kilt","knickers","knitwear","lapel","leggings","lingerie","loafers","longjohns","lycra","mandilion","mantua","mini-skirt","miniskirt","mob-cap","moccasin","neckerchief","necklace","necktie","neckwear","negligee","nightdress","nightgown","nightshirt","nightwear","overall","overalls","overcoat","pajamas","panniers","pantalettes","panties","pants","pantyhose","parkas","peacoat","peignoir","petticoat","pinafore","pocketwatch","polyester","poncho","porkpie","pullover","purse","pyjamas","qipao","raincoat","raingear","rastacap","ring","rings","robe","sandals","sash","satin","scarf","shirt","shirts","shoe","shorts","silk","skirt","slacks","sleeve","slippers","smock","smocking","sneakers","socks","sombrero","spandex","spats","stetson","stiletto","stockings","suit","suspender","sweater","sweatshirt","t-shirt","thong","tie","ties","tights","tracksuit","trousers","tuck","tuque","turban","undergarment","underpants","underwear","uniform","velvet","vest","waders","waistcoat","wallet","watch","wellingtons","wingtips");
// type = D
// type_sub = CL
$lang["clothing_details"] = array("cheongsam","chiffon","clothes","clothier","clothing","cotton","cuff","denim","dirndl","doublet","fabric","fashion","fashions","footwear","fourchettes","garment","garments","gauntlets","hem","hosiery","laces","lining","nylon","outerwear","pleat","pocket","seersucker","textiles","wool","zipper");
// type = A
// type_sub = CL
$lang["clothing_actions"] = array("sewing","patternmaking","dressing","dressed","wear","wearing");