<?php if (!defined("BASEPATH")) exit("No direct script access allowed");
// Food
// type = S
// type_sub = F
// sentiment = 1
$lang["food_positive"] = array("americano","apple","apples","applesauce","apricot","asparagus","bacon","banana","bananas","bean","beans","beef","berries","berry","beverage","beverages","biscuits","blackberry","blackberries","blueberry","blueberries","boba","broccoli","brownie","brownies","bun","buns","burrito","burritos","butter","cabbage","cacao","cake","cakes","calamari","cantaloupe","cantaloupes","cappuccino","cappuccinos","carrot","carrots","cauliflower","cauliflowers","celery","cereal","cheese","cherries","cherry","chicken","chili","chilies","habanero","habaneros","tabasco","chips","chocolate","chocolates","chops","cinnamon","cocoa","coffee","coffees","condiments","cookie","cookies","corn","corns","cornstarch","crabmeat","cracker","crackers","cream","creamer","egg","eggs","escargot","fish","flour","fruit","fruits","garlic","guava","guavas","ginger","granola","grapes","greenbeans","ham","hamburger","honey","horseradish","jackfruit","jackfruits","jello","jelly","kashi","ketchup","kiwi","kiwis","lasagne","latte","lemon","lemons","lettuce","lime","macaroni","macchiato","macchiatos","mango","mangos","margarine","mayonnaise","meat","meats","melon","melons","milk","millet","mocha","mushrooms","mustard","nectarines","noodles","nutmeg","nutella","nuts","oatmeal","olive","olives","onion","onions","oranges","oregano","pancake","pancakes","papaya","papayas","paprika","parsley","passionfruit","passionfruits","pasta","pastas","pea","peach","peaches","peanut","peanuts","pear","pears","peas","pepper","peppers","pineapple","pineapples","pizza","plums","popcorn","pork","porknbeans","potato","potatoes","powder","pretzels","quinoa","raisins","rice","roast","rotelle","salmon","salsa","salt","sauce","sauces","sausage","scallops","seafood","seasonings","shrimp","soda","sodas","soy","spaghetti","spelt","squash","steaks","strawberry","strawberries","taco","tacos","tapioca","taters","tomato","tomatoe","tomatoes","tortilla","tortillias","tuna","turkey","vanilla","veal","vegetable","vegetables","vemicelli","watermelon","worcestershire","yoghurt","yogurt","zucchini","poultry","venison","pate","wheat","acorn","acorns","breadnut","breadnuts","cashew","cashews","chestnuts","coconut","coconuts","hazelnut","hazelnuts","heartnut","macadamia","pecan","pecans","pistachio","pistachios","soybean","soybeans","walnut","walnuts","miso","sushi","sashimi","nori","tamari","wasabi","sesame","injera","naan","curry","curries","tikka","paneer");
// Taste
$lang["food_taste"] = array("acerbic","acidic","acrid","aftertaste","ambrosial","appetizing","argumentative","astringent","barnyardy","biting","bitter","bittersweet","bland","brackish","briny","buonissimo","buttery","byzantine","caustic","cibolic","citrousy","cornucopious","creamy","cressy","cuminic","curdy","delectable","delicious","dulcet","dulcify","flavor","flavorful","floral","freshy","fruity","gamey","gamy","garbled","garlicky","gelatinous","ghastly","groatsy","gustation","gustatory","honey","hork","hot","inducing","juicy","krillish","layered","loin","lovecraftian","luscious","minty","mouth","multi","nidorous","nutty","oily","oleaginous","pabulumy","palatable","palate","pannageous","peppery","perky","piquant","pongsome","pungent","pureed","quornish","rancid","rank","relish","saccharine","saline","salt","salty","savor","savory","scrumdiddilyumpshus","scrumptious","sharp","sludgy","smack","smoky","soapy","sour","spicy","stinging","stirring","sublime","succulant","succulent","sugary","tang","tart","taste","tasty","tender","tongue","toothsome","umami","unctuous","unexpectedly","velvety","vinegary","voluptuously","watering","woody","yummy","yummies","zest","zesty","alkaline","burnt","crisp","fishy","gingery","hearty","medicinal","mellow","overripe","raw","ripe","spoiled","sweet","tangy","tasteless","unripe");
// type = S
// sentiment = -1
$lang["food_negative"] = array("sugar","sugars","syrup","syrups","sweets","candy","candies","lard");
// type = D
// sentiment = 0
$lang["food_dietary"] = array("fat","fats","fatty","cholesterol","cholesterols","nutrients","nutritious","nutritiousness","protein","proteins","carbohydrate","carbohydrates","starch","starches","starchy","mineral","minerals","vitamin","vitamins","amino","aminos");
// Alcohol
// type = D, S, P
// type_sub = AL
// Sentiment = -1
$lang["alcohol_descriptor"] = array("alcohol","booze","booze-hound","booze-hounds","boozehound","boozehounds","boozer","boozers","boozes","booze-up","boozed","liquor","liquors");
$lang["alcohol_sensory"] 	= array("absinthe","akvavit","ale","arak","armagnac","arrack","baijiu","barleywine","beer","bitters","bock","bourbon","brandy","cacha","cask","cauim","champagne","chicha","cider","cognac","damassine","damson","de","eau","ggermeister","ggers","gin","gulu","hefeweizen","himbeergeist","horilka","huangjiu","icariine","jagger","jaggermeister","jerkum","kaoliang","kilju","kirsch","kumis","lager","liqueur","liqueurs","madeira","maotai","marsala","mead","metaxa","mezcal","mild","obstwasser","ogogoro","ouzo","pale","palinka","perry","pilsener","pisco","plum","poire","port","porter","pulque","rakia","rum","sahti","sake","sangria","schnapps","schwarzbier","scotch","sherry","slivovitz","sloe","small","soju","sonti","spirits","stock","stout","tepache","tequila","tiswin","tonto","vermouth","vie","vinsanto","vodka","whisky","williamine","williams","wine","wines","zwetschgenwasser");
$lang["alcohol_physical"] 	= array("drunkard","drunkards","drunk","sloshed");