<?php if (!defined("BASEPATH")) exit("No direct script access allowed");
// Sex
// type = I
// type_sub = SP
$lang["sexuality_s"] 		= array("type" => "S", "words" => array("sexualize","sexuality","sexual"));
// type = P
$lang["sexuality_p"]		= array("type" => "P", "words" => array("hookup","sensual","sensuality","sex","blowjob","biting","fuck","fucking","fucked","kiss","kissed","kissing","lick","licking","oral","cunnilingus","rimming","suck","sucking","rimjob","rimming","anal","sexy","sexually","voluptuous","curvy","thick","porn","ass","tits","boobs","boobies","breasts","pussy","cunt","penis","dick","cock","nipples","docking"));
// type = D
$lang["sexuality_d"]		= array("type" => "D", "words" => array("dildo","sybian","vibrators","vibrator","hitachi","uti","iud","condom","std","sti","sex toy","dental dam"));
// type = P
$lang["sexuality_kink_i"]	= array("type" => "I", "words" => array("boots","pigtails","thongs","corset","clingfilm","armbinders","corsetry","chastity","bdsm","cuckold","cuckolding","asphyxiaphilia","bastinado","bbbw","bbw","bondage","breathplay","bukkake","buttplug","caging","caning","cbt","cockrings","coprophilia","cosplay","creampie","cropping","cumbath","cunnilingus","cybelian","dacryphilia","diapers","dollification","domination","dommes","douching","edgeing","elastrators","electrostimulation","electrotorture","emetophilia","encasement","enslavement","eproctophilia","estim","eunuch","exhibitionism","facesitting","fellatio","feminization","femmedomme","figging","fishhooking","fishnets","fisting","flogging","footdom","footjobs","footworship","forniphilia","foursomes","frotage","ftm","fucking","fucktoy","furries","gagging","gags","gangbangs","garbage","garter","gas","gasmask","giantess","girdles","girls","gloryholes","goldenshowers","gorean","grappling","hairjob","hogtied","hojojutsu","intersexed","kinbaku","klismaphilia","kominikuv","lactation","lactophilia","latex","leotards","lezdom","maledom","masochism","mudbath","mummification","nappies","nunplay","objectification","oculolinctus","omorashi","oralsexslave","oralsuckslave","orgies","otk","pegging","phimosis","plaidaphile","podophilia","polyamory","priestplay","pussyboi","pvc","queening","ragdolling","restraint","resuscitation","retifism","rimming","romance","rosebud","rubber","sadism","sadist","scarification","shapewear","shemale","shibari","shoejob","shoeplay","silkscarves","sissification","sissified","slave","slaveboy","sleepsack","sluts","smothering","snowballing","snowsuits","somnophilia","spankings","speculums","speedos","spit","spitting","squashing","squirting","ssbbw","stim","straitjackets","strangulation","strappado","student","subspace","suits","superheroes","suppositories","suspension","swinging","sybians","t","teacher","teasing","threesomes","tightlacing","transvestism","turtlenecks","uncircumcised","uncut","urolagnia","vampirism","vorarephilia","voyeurism","wartenberg","waxing","whipping","whips","yiff","zentai"));